import type { LensKind } from "./render";

/**
 * The link an artifact travels along — ROADMAP step 7's *"every artifact in the
 * image links to the plot that explains it"*, and the wire format that keeps the
 * plot about the image you clicked.
 *
 * No DOM, no React: a string in, a checked object out, so the codec is testable
 * with no browser in the room. `saved.ts`'s pattern, and deliberately not its
 * payload — that one carries a microscope `BuildSpec` and this one carries the
 * five numbers a refractor image was made from.
 *
 * ## Why the link has to carry the optics at all
 *
 * A link that opened the ray fan on its own defaults would draw *a* lens rather
 * than **the** lens whose coma tail was just clicked, and the teaching claim —
 * "that flare is this curve" — would be false while looking exactly as
 * convincing. So the sender's slider state rides along, the receiving panel
 * seeds itself from it, and the two surfaces are provably the same system: both
 * hand these fields to `buildSystem`.
 *
 * ## Why it is the hash and not a slot
 *
 * `saved.ts` chose one `localStorage` slot over the URL and said why — a wire
 * format has to be versioned before the first link is shared. That reasoning was
 * about a *design a reader authored*, which is theirs and outlives the tab. A
 * teaching link is the opposite: it is generated by the app, consumed by the
 * next route, and dead a moment later. It has to survive a route change, which
 * unmounts the sender, and nothing longer. `registry.ts` already grants the
 * property that buys — *"`id` is the URL hash, so a route survives a reload and
 * can be linked to"* — so the hash is where a per-navigation payload belongs,
 * and the versioning `saved.ts` wanted is here anyway because it costs one
 * field.
 *
 * ## Every field is checked, and a bad link says so
 *
 * `decodeLink` returns `null` for anything it does not fully recognise — not a
 * partial link, and never a clamped one. A link whose aperture arrived as 400 mm
 * would otherwise draw a real curve for a lens nobody asked about, which is the
 * same failure `saved.ts` refuses in its own words: a payload that is 15/16 right
 * builds a *different lens* rather than failing. The panel's branch is then the
 * honest one — it seeds from its own defaults and prints that it did.
 */

/** Bump when `TeachingLink` changes shape; an older link then decodes to `null`. */
export const LINK_VERSION = 1;

/**
 * What a teaching link carries.
 *
 * The optics half is exactly the subset of `RenderRequest` that `buildSystem`
 * reads, so a receiving panel can rebuild the sender's system rather than
 * approximate it. `pupilSamples`, exposure and seeing are deliberately absent:
 * they change the picture, not the lens, and neither plot is a picture.
 */
export interface TeachingLink {
  readonly lens: LensKind;
  readonly focalLengthMm: number;
  readonly apertureMm: number;
  readonly sourceTemperatureK: number;
  readonly wavelengths: number;
  /**
   * The field angle of the artifact that sent the link, in degrees — which star
   * in the frame, not a sweep bound. 0 for a link from an on-axis image.
   */
  readonly fieldDeg: number;
  /** Route id of the surface that sent it, so the plot can offer the way back. */
  readonly from: string;
}

/**
 * The accepted range of each number, and it is not decoration.
 *
 * These are the sender's own slider bounds plus the physical facts underneath
 * them (a diameter is positive; a field angle is not negative). A value outside
 * is a link this app did not write, so it is refused rather than trusted — see
 * the header. `fieldDeg` runs a little past the star grid's corner (√2 × 0.8°)
 * so a corner star is inside its own bound rather than on it.
 */
const RANGE = {
  focalLengthMm: [1, 10_000],
  apertureMm: [0.1, 1_000],
  sourceTemperatureK: [1_000, 40_000],
  wavelengths: [3, 31],
  fieldDeg: [0, 5],
} as const satisfies Record<string, readonly [number, number]>;

const LENSES: readonly LensKind[] = ["singlet", "achromat"];

/** A route id: what `registry.ts` matches on, so the same shape a hash has. */
const ROUTE = /^[a-z][a-z0-9-]{0,31}$/;

/** The query half of a teaching hash — `#/rayfan?…`, without the `?`. */
export function encodeLink(link: TeachingLink): string {
  const q = new URLSearchParams();
  q.set("v", String(LINK_VERSION));
  q.set("lens", link.lens);
  q.set("f", String(link.focalLengthMm));
  q.set("a", String(link.apertureMm));
  q.set("t", String(link.sourceTemperatureK));
  q.set("w", String(link.wavelengths));
  // Six decimals is ~4 µdeg on a 1° field — far below anything the trace
  // resolves, and it keeps a corner star's √2 from filling the address bar.
  q.set("fld", link.fieldDeg.toFixed(6));
  q.set("from", link.from);
  return q.toString();
}

/** A whole hash, ready for an `href`. */
export function linkHref(route: string, link: TeachingLink): string {
  return `#${route}?${encodeLink(link)}`;
}

function numberIn(raw: string | null, [lo, hi]: readonly [number, number]): number | null {
  if (raw === null || raw.trim() === "") return null;
  const value = Number(raw);
  if (!Number.isFinite(value)) return null;
  return value >= lo && value <= hi ? value : null;
}

/**
 * A query string back to a link, or `null` — never a partial or clamped one.
 *
 * `null` covers every way this goes wrong at once: a version this code does not
 * know, a missing field, a field that is not a number, a number outside the
 * range the app can have written. One branch for the caller, and it is the
 * branch that tells the reader the link did not survive.
 */
export function decodeLink(query: string): TeachingLink | null {
  const q = new URLSearchParams(query);
  if (q.get("v") !== String(LINK_VERSION)) return null;

  const lens = q.get("lens");
  if (lens === null || !LENSES.includes(lens as LensKind)) return null;

  const focalLengthMm = numberIn(q.get("f"), RANGE.focalLengthMm);
  const apertureMm = numberIn(q.get("a"), RANGE.apertureMm);
  const sourceTemperatureK = numberIn(q.get("t"), RANGE.sourceTemperatureK);
  const wavelengths = numberIn(q.get("w"), RANGE.wavelengths);
  const fieldDeg = numberIn(q.get("fld"), RANGE.fieldDeg);
  if (
    focalLengthMm === null ||
    apertureMm === null ||
    sourceTemperatureK === null ||
    wavelengths === null ||
    fieldDeg === null
  ) {
    return null;
  }
  // A count that arrived as 8.5 is not a count. Checked rather than rounded:
  // rounding would accept a link this app cannot have written.
  if (!Number.isInteger(wavelengths)) return null;

  const from = q.get("from");
  if (from === null || !ROUTE.test(from)) return null;

  return {
    lens: lens as LensKind,
    focalLengthMm,
    apertureMm,
    sourceTemperatureK,
    wavelengths,
    fieldDeg,
    from,
  };
}
